DELETE FROM Rentals;
DELETE FROM Blurays;
DELETE FROM SupportFilms;
DELETE FROM Films;
DELETE FROM SubscriberCards;
DELETE FROM SupportCards;
DELETE FROM Subscribers;
DELETE FROM Logins;
DELETE FROM CreditCards;